version: "2.0"
x-service: &deepbi-service
  build:
    context: .
  volumes:
    - .:/app
  env_file:
    - .env
x-environment: &deepbi-environment
  DEEPBI_LOG_LEVEL: "INFO"
  DEEPBI_RATELIMIT_ENABLED: "false"
  DEEPBI_MAIL_DEFAULT_SENDER: "test@example.com"
  DEEPBI_MAIL_SERVER: "email"
  DEEPBI_ENFORCE_CSRF: "true"
  DEEPBI_GUNICORN_TIMEOUT: 60
  DEEPBI_WEB_WORKERS: 4
  DEEPBI_CELERY_WORKERS: 4
services:
  server:
    <<: *deepbi-service
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "8338:8338"
    environment:
      <<: *deepbi-environment
      PYTHONUNBUFFERED: 0
  server_ai_api:
    <<: *deepbi-service
    command: server_api
    depends_on:
      - server
    ports:
      - "8340:8340"
    environment:
      <<: *deepbi-environment
  server_socket:
    <<: *deepbi-service
    command: server_socket
    depends_on:
      - server
    ports:
      - "8339:8339"
    environment:
      <<: *deepbi-environment
  scheduler:
    <<: *deepbi-service
    command: scheduler
    depends_on:
      - server
    environment:
      <<: *deepbi-environment
  worker:
    <<: *deepbi-service
    command: worker
    depends_on:
      - server
    environment:
      <<: *deepbi-environment
      PYTHONUNBUFFERED: 0
  redis:
    image: redis:3-alpine
    restart: unless-stopped
  postgres:
    image: postgres:14-alpine
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  email:
    image: maildev/maildev
    ports:
      - "1080:80"
    restart: unless-stopped
